// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeLoginToken = `-- name: ConsumeLoginToken :one
UPDATE login_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > $2
RETURNING id, email, token_hash, expires_at, used_at, created_at
`

type ConsumeLoginTokenParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ConsumeLoginToken(ctx context.Context, arg ConsumeLoginTokenParams) (LoginToken, error) {
	row := q.db.QueryRow(ctx, consumeLoginToken, arg.TokenHash, arg.ExpiresAt)
	var i LoginToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLoginToken = `-- name: CreateLoginToken :one
INSERT INTO login_tokens (email, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, email, token_hash, expires_at, used_at, created_at
`

type CreateLoginTokenParams struct {
	Email     string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateLoginToken(ctx context.Context, arg CreateLoginTokenParams) (LoginToken, error) {
	row := q.db.QueryRow(ctx, createLoginToken, arg.Email, arg.TokenHash, arg.ExpiresAt)
	var i LoginToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const firstHomeForUser = `-- name: FirstHomeForUser :one
SELECT h.id, h.name, h.created_at, m.id AS member_id FROM members m JOIN homes h ON h.id = m.home_id
WHERE m.user_id = $1 ORDER BY m.id LIMIT 1
`

type FirstHomeForUserRow struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	MemberID  int64
}

func (q *Queries) FirstHomeForUser(ctx context.Context, userID int64) (FirstHomeForUserRow, error) {
	row := q.db.QueryRow(ctx, firstHomeForUser, userID)
	var i FirstHomeForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.MemberID,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.display_name, u.created_at FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > $2
`

type GetSessionUserParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, arg.TokenHash, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}
