// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: homes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHome = `-- name: CreateHome :one
INSERT INTO homes (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateHome(ctx context.Context, name string) (Home, error) {
	row := q.db.QueryRow(ctx, createHome, name)
	var i Home
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (home_id, user_id) VALUES ($1, $2)
ON CONFLICT (home_id, user_id) DO UPDATE SET home_id = EXCLUDED.home_id
RETURNING id, home_id, user_id, created_at
`

type CreateMemberParams struct {
	HomeID int64
	UserID int64
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.HomeID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFact = `-- name: DeleteFact :exec
DELETE FROM facts WHERE home_id = $1 AND key = $2
`

type DeleteFactParams struct {
	HomeID int64
	Key    string
}

func (q *Queries) DeleteFact(ctx context.Context, arg DeleteFactParams) error {
	_, err := q.db.Exec(ctx, deleteFact, arg.HomeID, arg.Key)
	return err
}

const getHome = `-- name: GetHome :one
SELECT id, name, created_at FROM homes WHERE id = $1
`

func (q *Queries) GetHome(ctx context.Context, id int64) (Home, error) {
	row := q.db.QueryRow(ctx, getHome, id)
	var i Home
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listFacts = `-- name: ListFacts :many
SELECT id, home_id, key, value, source, updated_at FROM facts WHERE home_id = $1 ORDER BY key
`

func (q *Queries) ListFacts(ctx context.Context, homeID int64) ([]Fact, error) {
	rows, err := q.db.Query(ctx, listFacts, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fact
	for rows.Next() {
		var i Fact
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.Key,
			&i.Value,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.home_id, m.user_id, m.created_at, u.email, u.display_name
FROM members m JOIN users u ON u.id = m.user_id
WHERE m.home_id = $1 ORDER BY m.id
`

type ListMembersRow struct {
	ID          int64
	HomeID      int64
	UserID      int64
	CreatedAt   pgtype.Timestamptz
	Email       string
	DisplayName string
}

func (q *Queries) ListMembers(ctx context.Context, homeID int64) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.UserID,
			&i.CreatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFact = `-- name: UpsertFact :one
INSERT INTO facts (home_id, key, value, source) VALUES ($1, $2, $3, $4)
ON CONFLICT (home_id, key) DO UPDATE SET value = EXCLUDED.value, source = EXCLUDED.source, updated_at = now()
RETURNING id, home_id, key, value, source, updated_at
`

type UpsertFactParams struct {
	HomeID int64
	Key    string
	Value  []byte
	Source string
}

func (q *Queries) UpsertFact(ctx context.Context, arg UpsertFactParams) (Fact, error) {
	row := q.db.QueryRow(ctx, upsertFact,
		arg.HomeID,
		arg.Key,
		arg.Value,
		arg.Source,
	)
	var i Fact
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.Key,
		&i.Value,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}
