// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites SET used_at = now()
WHERE code_hash = $1 AND used_at IS NULL AND expires_at > $2
RETURNING id, home_id, created_by, code_hash, expires_at, used_at, created_at
`

type ConsumeInviteParams struct {
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, arg.CodeHash, arg.ExpiresAt)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.CreatedBy,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (home_id, created_by, code_hash, expires_at) VALUES ($1, $2, $3, $4) RETURNING id, home_id, created_by, code_hash, expires_at, used_at, created_at
`

type CreateInviteParams struct {
	HomeID    int64
	CreatedBy int64
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.HomeID,
		arg.CreatedBy,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.CreatedBy,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
