// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Completion struct {
	ID          int64
	TaskID      int64
	MemberID    int64
	CompletedAt pgtype.Timestamptz
}

type Fact struct {
	ID        int64
	HomeID    int64
	Key       string
	Value     []byte
	Source    string
	UpdatedAt pgtype.Timestamptz
}

type Home struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Invite struct {
	ID        int64
	HomeID    int64
	CreatedBy int64
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type LoginToken struct {
	ID        int64
	Email     string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Member struct {
	ID        int64
	HomeID    int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type Rule struct {
	ID         string
	Version    int32
	Definition []byte
	UpdatedAt  pgtype.Timestamptz
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Task struct {
	ID           int64
	HomeID       int64
	RuleID       *string
	Title        string
	Detail       string
	IntervalDays int32
	SeasonStart  *string
	SeasonEnd    *string
	StartDate    pgtype.Date
	ArchivedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID          int64
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}
