// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package db

import (
	"context"
)

const listRules = `-- name: ListRules :many
SELECT id, version, definition, updated_at FROM rules ORDER BY id
`

func (q *Queries) ListRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Definition,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRule = `-- name: UpsertRule :one
INSERT INTO rules (id, version, definition) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, definition = EXCLUDED.definition, updated_at = now()
RETURNING id, version, definition, updated_at
`

type UpsertRuleParams struct {
	ID         string
	Version    int32
	Definition []byte
}

func (q *Queries) UpsertRule(ctx context.Context, arg UpsertRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, upsertRule, arg.ID, arg.Version, arg.Definition)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Definition,
		&i.UpdatedAt,
	)
	return i, err
}
