// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTask = `-- name: ArchiveTask :exec
UPDATE tasks SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveTask, id)
	return err
}

const createCompletion = `-- name: CreateCompletion :one
INSERT INTO completions (task_id, member_id, completed_at) VALUES ($1, $2, $3) RETURNING id, task_id, member_id, completed_at
`

type CreateCompletionParams struct {
	TaskID      int64
	MemberID    int64
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) CreateCompletion(ctx context.Context, arg CreateCompletionParams) (Completion, error) {
	row := q.db.QueryRow(ctx, createCompletion, arg.TaskID, arg.MemberID, arg.CompletedAt)
	var i Completion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.MemberID,
		&i.CompletedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (home_id, rule_id, title, detail, interval_days, season_start, season_end, start_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, home_id, rule_id, title, detail, interval_days, season_start, season_end, start_date, archived_at, created_at
`

type CreateTaskParams struct {
	HomeID       int64
	RuleID       *string
	Title        string
	Detail       string
	IntervalDays int32
	SeasonStart  *string
	SeasonEnd    *string
	StartDate    pgtype.Date
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.HomeID,
		arg.RuleID,
		arg.Title,
		arg.Detail,
		arg.IntervalDays,
		arg.SeasonStart,
		arg.SeasonEnd,
		arg.StartDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.RuleID,
		&i.Title,
		&i.Detail,
		&i.IntervalDays,
		&i.SeasonStart,
		&i.SeasonEnd,
		&i.StartDate,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, home_id, rule_id, title, detail, interval_days, season_start, season_end, start_date, archived_at, created_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.RuleID,
		&i.Title,
		&i.Detail,
		&i.IntervalDays,
		&i.SeasonStart,
		&i.SeasonEnd,
		&i.StartDate,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const latestCompletions = `-- name: LatestCompletions :many
SELECT DISTINCT ON (c.task_id) c.id, c.task_id, c.member_id, c.completed_at
FROM completions c JOIN tasks t ON t.id = c.task_id
WHERE t.home_id = $1
ORDER BY c.task_id, c.completed_at DESC
`

func (q *Queries) LatestCompletions(ctx context.Context, homeID int64) ([]Completion, error) {
	rows, err := q.db.Query(ctx, latestCompletions, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Completion
	for rows.Next() {
		var i Completion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.MemberID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTasks = `-- name: ListActiveTasks :many
SELECT id, home_id, rule_id, title, detail, interval_days, season_start, season_end, start_date, archived_at, created_at FROM tasks WHERE home_id = $1 AND archived_at IS NULL ORDER BY id
`

func (q *Queries) ListActiveTasks(ctx context.Context, homeID int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listActiveTasks, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.RuleID,
			&i.Title,
			&i.Detail,
			&i.IntervalDays,
			&i.SeasonStart,
			&i.SeasonEnd,
			&i.StartDate,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
